# Generated by Django 3.2.4 on 2021-09-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_group_s_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='S_User',
            new_name='Suser',
        ),
    ]
