# Generated by Django 3.2.4 on 2021-09-24 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_s_user_suser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='some_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='suser',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='suser',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.group'),
        ),
    ]
