# Generated by Django 3.2.4 on 2021-10-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210924_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromiscuousUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('group', models.ManyToManyField(null=True, to='polls.Group')),
            ],
        ),
    ]
